#!/bin/sh
PATCH_PRE=add-onscreen-keyboard.patch
PATCH_EMU=add-onscreen-keyboard-emu.patch
PATCH=${PATCH_PRE}

if [ "$1" = "emulator" ]
then
  EMULATOR=yes
  cd /opt/src/modifications/frameworks
  rm -f ${PATCH_EMU}
  git pull
  sed s/191_15/191_14/g ${PATCH_PRE} > tmp
  sed s/191.15/191.14/g tmp > ${PATCH_EMU}
  rm -f tmp
  PATCH=${PATCH_EMU}
fi

sh /opt/src/modifications/install ${PATCH}
if [ $? -ne 0 ]
then
  echo "ERROR: Could not install patch!"
  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
  exit 1
fi

if [ "$EMULATOR" = "" ]
then
  echo "Remounting / rw..."
  mount -o rw,remount /
  if [ $? -ne 0 ]
  then
    echo "ERROR: Could not remount / in rw"
    echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
    exit 1
  fi
fi

cp /opt/src/modifications/frameworks/virtual-keyboard-themes.tar.gz / && cd / && tar -xvzf virtual-keyboard-themes.tar.gz && cd - && echo "SUCCESS"

if [ "$EMULATOR" = "" ]
then
  echo "Remounting / to read-only"
  mount -o ro,remount /
fi
