#!/bin/sh
sh /opt/src/modifications/install add-onscreen-keyboard.patch
if [ $? -ne 0 ]
then
  echo "ERROR: Could not install patch!"
  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
  exit 1
fi

echo "Remounting / rw..."
mount -o rw,remount /
if [ $? -ne 0 ]
then
  echo "ERROR: Could not remount / in rw"
  echo "Please visit http://www.webos-internals.org/wiki/Applying_Patches"
  exit 1
fi

cp /opt/src/modifications/frameworks/virtual-keyboard-themes.tar.gz / && cd / && tar -xvzf virtual-keyboard-themes.tar.gz && cd - && echo "SUCCESS"

echo "Remounting / to read-only"
mount -o ro,remount /

